version: '3.8'

services:
  numvalidate:
    build: .
    container_name: numvalidate
    restart: unless-stopped
    ports:
      - "8088:8080"
    networks:
      - n8n-net
      - dokploy-net

networks:
  n8n-net:
    name: n8n-n8n-imv5re
    external: true
  dokploy-net:
    name: dokploy-network
    external: true
